### ISSUE TITLE
WHMCS Callback Issue - Data has been tampered

### ISSUE THREAD

**Issue by syafi-dev** [Billplz/Billplz-for-WHMCS#3]
Hi,

After user make payment from whmcs to billplz, it return Data has been tampered and invoice status not updated to PAID.

Kindly please help to fix it. 

WHMCS Version : 8.1.3

**Comment by wzul** [comment]
Hi.

Kindly check your X Signature Key value. Alternatively, you might be interested in upgrading the plugin as follows:

- Have a full backup
- Rename table `mod_billplz_gateway` to `mod_billplz_gateway_old`
- Delete folder `/modules/gateways/billplzPay`
- Download overwrite the plugin files to your installation directory
- Re-configure API Key, Collection ID and X Signature Key

Hope this helps.
